exports.seed = function (knex) {
  // Deletes ALL existing entries
  // Inserts seed entries
  return knex("watches").insert([
    {
      id: 1,
      name: "rowValue1",
      img: "test",
      description: "bitcoin watch",
      intial_cost: "1 BTC",
    },
    {
      id: 2,
      name: "rowValue2",
      img: "test",
      description: "bitcoin watch",
      intial_cost: "1 BTC",
    },
    {
      id: 3,
      name: "a",
      img: "test",
      description: "bitcoin watch",
      intial_cost: "1 BTC",
    },
    {
      id: 4,
      name: "b",
      img: "test",
      description: "bitcoin watch",
      intial_cost: "1 BTC",
    },
    // {
    //   id: 5,
    //   name: "c",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 6,
    //   name: "d",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 7,
    //   name: "e",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 8,
    //   name: "f",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 9,
    //   name: "g",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 10,
    //   name: "h",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 11,
    //   name: "i",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 12,
    //   name: "j",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 13,
    //   name: "k",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 14,
    //   name: "l",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 15,
    //   name: "m",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 16,
    //   name: "n",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 17,
    //   name: "o",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 18,
    //   name: "p",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 19,
    //   name: "q",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 20,
    //   name: "r",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
    // {
    //   id: 21,
    //   name: "s",
    //   img: "test",
    //   description: "bitcoin watch",
    //   intial_cost: "1 BTC",
    // },
  ]);
};
